Repository Autodesk/hig, pull requests merged in 2019-01, with the labels that each got.

#1517 Release: January 8, 2019
  acceptance/package.json
  acceptance/src/pages/InputPage.js
  acceptance/src/pages/TypographyPage.js
  acceptance/src/routes.js
  acceptance/yarn.lock
  packages/button/package.json
  packages/checkbox/package.json
  packages/components/package.json
  packages/input/package.json
  packages/notifications-flyout/package.json
  packages/profile-flyout/package.json
  packages/project-account-switcher/package.json
  packages/project-account-switcher/src/behavior/ProjectAccountSwitcherBehavior.js
  packages/storybook/gemini/chromeReact/Typography/All Variations/All Variations/chromeReact.png
  packages/theme-data/src/basics/lineHeights.js
  packages/theme-data/src/densities/highDensity/components/typography.js
  packages/theme-data/src/densities/highDensity/unresolvedRoles.js
  packages/theme-data/src/densities/mediumDensity/components/typography.js
  packages/theme-data/src/densities/mediumDensity/unresolvedRoles.js
  packages/tooltip/package.json
  packages/top-nav/package.json
  packages/typography/README.md
  packages/typography/src/Typography.test.js
  packages/typography/src/__gemini__/Typography.stories-test.js
  packages/typography/src/__snapshots__/Typography.test.js.snap
  packages/typography/src/_constants.js
  yarn.lock
Labels: release

#1526 Release: January 9, 2019
  acceptance/package.json
  acceptance/src/components/ThemeRepeater.js
  acceptance/src/pages/AvatarPage.js
  acceptance/src/pages/IconsPage.js
  acceptance/src/routes.js
  acceptance/yarn.lock
  packages/avatar/package.json
  packages/avatar/src/Avatar.js
  packages/flyout/package.json
  packages/flyout/src/Flyout.js
  packages/label/package.json
  packages/label/src/__snapshots__/Label.test.js.snap
  packages/label/src/stylesheet.js
  packages/profile-flyout/src/presenters/__snapshots__/ProfileButtonPresenter.test.js.snap
  packages/storybook/gemini/chromeReact/Label/Default/chromeReact.png
  packages/storybook/gemini/chromeReact/NotificationsFlyout/default/Default/chromeReact.png
  packages/storybook/gemini/chromeReact/ProfileFlyout/default/default/chromeReact.png
  packages/storybook/gemini/chromeReact/ProfileFlyout/with children/with children/chromeReact.png
  packages/top-nav/src/presenters/__snapshots__/ProfileButtonPresenter.test.js.snap
  packages/typography/package.json
Labels: release

#1501 Add Slider theme data
  packages/theme-data/src/baseTheme/components/slider.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/basics/colors.js
  packages/theme-data/src/colorSchemes/darkBlue/components/slider.js
  packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/lightGray/unresolvedRoles.js
Labels: theme data

#1532 Add Tooltip theme data
  packages/theme-data/src/baseTheme/components/tooltip.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/darkBlue/components/tooltip.js
  packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/darkGray/components/tooltip.js
  packages/theme-data/src/colorSchemes/darkGray/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/webLight/components/_oldColors.js
  packages/theme-data/src/colorSchemes/webLight/components/tooltip.js
  packages/theme-data/src/colorSchemes/webLight/unresolvedRoles.js
Labels: 1pt, theme data

#1560 Release: January 23, 2019
  .circleci/config.yml
  DEVELOPING.md
  packages/avatar/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/checkbox/src/__snapshots__/Checkbox.test.js.snap
  packages/checkbox/src/presenters/__snapshots__/CheckPresenter.test.js.snap
  packages/checkbox/src/presenters/__snapshots__/CheckboxPresenter.test.js.snap
  packages/checkbox/src/presenters/stylesheet.js
  packages/components/package.json
  packages/flyout/package.json
  packages/icons/package.json
  packages/input/package.json
  packages/label/package.json
  packages/notifications-flyout/package.json
  packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap
  packages/profile-flyout/README.md
  packages/profile-flyout/package.json
  packages/profile-flyout/src/__snapshots__/ProfileFlyout.test.js.snap
  packages/profile-flyout/src/__stories__/ProfileFlyout.stories.js
  packages/profile-flyout/src/__stories__/renderStory.js
  packages/profile-flyout/src/presenters/ProfileButtonPresenter.js
  packages/profile-flyout/src/presenters/ProfileButtonPresenter.scss
  packages/profile-flyout/src/presenters/ProfileContentPresenter.js
  packages/profile-flyout/src/presenters/ProfileContentPresenter.scss
  packages/profile-flyout/src/presenters/__snapshots__/ProfileButtonPresenter.test.js.snap
  packages/profile-flyout/src/presenters/__snapshots__/ProfileContentPresenter.test.js.snap
  packages/profile-flyout/src/presenters/stylesheet.js
  packages/progress-bar/package.json
  packages/project-account-switcher/package.json
  packages/project-account-switcher/src/__snapshots__/ProjectAccountSwitcher.test.js.snap
  packages/radio-button/package.json
  packages/skeleton-item/package.json
  packages/spacer/package.json
  packages/storybook/gemini/chromeReact/CheckboxPresenter/checked/checked - focused/chromeReact.png
  packages/storybook/gemini/chromeReact/CheckboxPresenter/checked/checked - unfocused/chromeReact.png
  packages/storybook/gemini/chromeReact/NotificationsFlyout/default/Default/chromeReact.png
  packages/storybook/package.json
  packages/theme-data/src/baseTheme/components/checkbox.js
  packages/theme-data/src/baseTheme/components/label.js
  packages/theme-data/src/baseTheme/components/progressRing.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/darkBlue/components/checkbox.js
  packages/theme-data/src/colorSchemes/darkBlue/components/label.js
  packages/theme-data/src/colorSchemes/lightGray/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/webLight/components/label.js
  packages/theme-data/src/colorSchemes/webLight/unresolvedRoles.js
  packages/tooltip/package.json
  packages/tooltip/src/__snapshots__/Tooltip.test.js.snap
  packages/top-nav/package.json
  packages/typography/package.json
  yarn.lock
Labels: release

#1535 feat: add theme data for text link
  packages/theme-data/src/baseTheme/components/textLink.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/basics/colors.js
  packages/theme-data/src/colorSchemes/darkBlue/components/textLink.js
  packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/webLight/components/_oldColors.js
  packages/theme-data/src/colorSchemes/webLight/components/textLink.js
  packages/theme-data/src/colorSchemes/webLight/unresolvedRoles.js
Labels: 1pt, theme data

#1596 Release: January 29, 2019
  packages/components/package.json
  packages/icons/package.json
  packages/icons/src/__stories__/Icons.stories.js
  packages/input/src/presenters/InputPresenter.stylesheet.js
  packages/input/src/presenters/__snapshots__/InputPresenter.test.js.snap
  packages/theme-data/src/baseTheme/components/input.js
  packages/theme-data/src/colorSchemes/darkBlue/components/input.js
  packages/theme-data/src/colorSchemes/lightGray/components/input.js
  packages/theme-data/src/colorSchemes/lightGray/unresolvedRoles.js
  packages/theme-data/src/densities/highDensity/components/input.js
  packages/theme-data/src/utils/extendTheme.js
  packages/theme-data/src/utils/mapValues.js
  packages/typography/package.json
  packages/typography/src/__stories__/Typography.stories.js
  packages/typography/src/index.js
  yarn.lock
Labels: release
