Repository Autodesk/hig, pull requests merged in 2019-08, with the labels that each got.

#1989 Release: August 1, 2019
  CONTRIBUTING.md
  DEVELOPING.md
  WindowsSetup.md
  acceptance/package-lock.json
  acceptance/package.json
  acceptance/src/components/MuiThemeRepeater.js
  acceptance/src/pages/material-ui/ButtonsPage.js
  acceptance/src/routes.js
  acceptance/yarn.lock
  packages/banner/src/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap
  packages/components/package.json
  packages/icon-button/src/IconButton.js
  packages/icon-button/src/__gemini__/IconButton.gemini.js
  packages/icon-button/src/__gemini__/IconButton.stories-test.js
  packages/icon-button/src/__snapshots__/IconButton.test.js.snap
  packages/icon-button/src/__stories__/getKnobs.js
  packages/icon-button/src/constants.js
  packages/icon-button/src/constants.test.js
  packages/icon-button/src/presenters/IconButtonPresenter.js
  packages/icon-button/src/presenters/__snapshots__/IconButtonPresenter.test.js.snap
  packages/icon-button/src/presenters/stylesheet.js
  packages/icon-button/src/presenters/stylesheet.test.js
  packages/modal/src/__snapshots__/Modal.test.js.snap
  packages/modal/src/presenters/__snapshots__/ModalHeaderPresenter.test.js.snap
  packages/modal/src/presenters/__snapshots__/ModalPresenter.test.js.snap
  packages/notifications-flyout/src/__snapshots__/Notification.test.js.snap
  packages/notifications-flyout/src/__snapshots__/NotificationsFlyout.test.js.snap
  packages/notifications-flyout/src/presenters/__snapshots__/DismissButtonPresenter.test.js.snap
  packages/notifications-flyout/src/presenters/__snapshots__/IndicatorPresenter.test.js.snap
  packages/notifications-flyout/src/presenters/__snapshots__/NotificationPresenter.test.js.snap
  packages/storybook/gemini/chromeReact/IconButton/Default/Default/chromeReact.png
  packages/storybook/gemini/chromeReact/IconButton/static/static/chromeReact.png
  packages/theme-data/src/baseTheme/components/iconButton.js
  packages/theme-data/src/colorSchemes/darkBlue/components/iconButton.js
  packages/theme-data/src/colorSchemes/darkGray/components/iconButton.js
  packages/theme-material-ui/CHANGELOG.md
  packages/theme-material-ui/README.md
  packages/theme-material-ui/material-themes.test.js
  packages/theme-material-ui/package.json
  packages/theme-material-ui/scripts/buildThemes.js
  packages/top-nav/src/presenters/__snapshots__/HelpButtonPresenter.test.js.snap
Labels: release

#1990 Greenkeeper/default/@hig/icon button 2.2.0
  packages/banner/package.json
  packages/components/package.json
  packages/modal/package.json
  packages/notifications-flyout/package.json
  packages/notifications-toast/package.json
  packages/side-nav/package.json
  packages/top-nav/package.json
Labels: greenkeeper

#1997 Release: August 2, 2019
  packages/banner/package.json
  packages/components/package.json
  packages/flyout/src/Flyout.js
  packages/flyout/src/Flyout.test.js
  packages/flyout/src/__snapshots__/Flyout.test.js.snap
  packages/flyout/src/presenters/FlyoutPresenter.js
  packages/flyout/src/presenters/PanelContainerPresenter.js
  packages/flyout/src/presenters/PanelPresenter.js
  packages/flyout/src/presenters/PointerPresenter.js
  packages/flyout/src/presenters/PointerWrapperPresenter.js
  packages/icon-button/src/presenters/__snapshots__/IconButtonPresenter.test.js.snap
  packages/icon-button/src/presenters/stylesheet.js
  packages/modal/package.json
  packages/modal/src/Modal.js
  packages/modal/src/Modal.test.js
  packages/modal/src/__snapshots__/Modal.test.js.snap
  packages/modal/src/presenters/ModalHeaderPresenter.js
  packages/modal/src/presenters/ModalPresenter.js
  packages/notifications-flyout/package.json
  packages/notifications-toast/package.json
  packages/side-nav/package.json
  packages/storybook/gemini/chromeReact/IconButton/static/static/chromeReact.png
  packages/top-nav/package.json
  packages/utils/package.json
  packages/utils/src/createCustomClassNames.js
  packages/utils/src/createCustomClassNames.test.js
  packages/utils/src/index.js
Labels: release

#1999 Release: August 2, 2019
  packages/flyout/package.json
  packages/modal/package.json
  packages/multi-downshift/package.json
  packages/notifications-flyout/package.json
  packages/profile-flyout/package.json
  packages/project-account-switcher/package.json
  packages/side-nav/package.json
  packages/slider/package.json
  packages/theme-data/src/baseTheme/components/thumbnail.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/darkBlue/components/thumbnail.js
  packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/darkGray/components/thumbnail.js
  packages/theme-data/src/colorSchemes/darkGray/unresolvedRoles.js
  packages/top-nav/package.json
Labels: release

#2006 Release: August 7, 2019
  packages/banner/src/BannerAction/__snapshots__/BannerAction.test.js.snap
  packages/banner/src/BannerAction/stylesheet.js
  packages/components/package.json
  packages/icon-button/package.json
  packages/icon-button/src/presenters/IconButtonPresenter.js
  packages/icon-button/src/presenters/IconButtonPresenter.test.js
  packages/icon-button/src/presenters/__snapshots__/IconButtonPresenter.test.js.snap
  packages/input/src/presenters/InputHaloPresenter.stylesheet.js
  packages/storybook/gemini/chromeReact/Dropdown/default/default - clicked/chromeReact.png
Labels: release

#2007 Chore/greenkeeper update
  packages/components/package.json
  packages/dropdown/package.json
  packages/modal/package.json
  packages/notifications-flyout/package.json
  packages/notifications-toast/package.json
  packages/side-nav/package.json
  packages/text-area/package.json
  packages/top-nav/package.json
Labels: greenkeeper

#2018 Release: August 8, 2019
  packages/button/README.md
  packages/button/package.json
  packages/button/src/presenters/ButtonPresenter.js
  packages/components/package.json
  packages/dropdown/README.md
  packages/dropdown/package.json
  packages/flyout/README.md
  packages/icon-button/README.md
  packages/input/README.md
  packages/modal/README.md
  packages/modal/package.json
  packages/notifications-flyout/package.json
  packages/notifications-toast/package.json
  packages/side-nav/package.json
  packages/side-nav/src/__stories__/SideNavCompact.stories.js
  packages/side-nav/src/__stories__/SideNavSubcomponents.stories.js
  packages/text-area/README.md
  packages/text-area/package.json
  packages/theme-data/README.md
  packages/theme-data/src/baseTheme/components/modal.js
  packages/top-nav/package.json
Labels: release

#2023 fix: remove non-existant theme-data role from stylesheet
  packages/icon-button/src/presenters/stylesheet.js
Labels: bug
