Repository Autodesk/hig, pull requests merged in 2020-07, with the labels that each got.

#2239 Release: July 10, 2020
  packages/avatar/src/__snapshots__/Avatar.test.js.snap
  packages/banner/src/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap
  packages/input/src/presenters/__snapshots__/InputHaloPresenter.test.js.snap
  packages/progress-ring/src/presenters/__snapshots__/ProgressRingPresenter.test.js.snap
  packages/storybook/gemini/chromeReact/Avatar/Default/chromeReact.png
  packages/storybook/gemini/chromeReact/Input/Dark blue high density/Dark blue high density/chromeReact.png
  packages/storybook/gemini/chromeReact/Input/Dark blue medium density/Dark blue medium density/chromeReact.png
  packages/storybook/gemini/chromeReact/ProgressRing/determinate default/default/chromeReact.png
  packages/storybook/gemini/chromeReact/ProgressRing/determinate extra large/extra-large/chromeReact.png
  packages/storybook/gemini/chromeReact/ProgressRing/determinate large/large/chromeReact.png
  packages/storybook/gemini/chromeReact/ProgressRing/determinate medium/medium/chromeReact.png
  packages/storybook/gemini/chromeReact/ProgressRing/determinate small/small/chromeReact.png
  packages/storybook/gemini/chromeReact/Slider/default/default/chromeReact.png
  packages/storybook/gemini/chromeReact/Slider/default/pressing the first Slider/chromeReact.png
  packages/storybook/gemini/chromeReact/Slider/disabled/disabled/chromeReact.png
  packages/storybook/gemini/chromeReact/Toggle/All Variations/All Variations/chromeReact.png
  packages/tabs/src/Tab.js
  packages/tabs/src/Tabs.js
  packages/tabs/src/Tabs.stylesheet.js
  packages/tabs/src/Tabs.stylesheet.test.js
  packages/tabs/src/presenters/ContentPresenter.js
  packages/tabs/src/presenters/ContentPresenter.stylesheet.js
  packages/tabs/src/presenters/ContentPresenter.stylesheet.test.js
  packages/tabs/src/presenters/Tab.stylesheet.js
  packages/tabs/src/presenters/Tab.stylesheet.test.js
  packages/tabs/src/presenters/TabCloseButtonPresenter.js
  packages/tabs/src/presenters/TabCloseButtonPresenter.stylesheet.js
  packages/tabs/src/presenters/TabCloseButtonPresenter.stylesheet.test.js
  packages/tabs/src/presenters/TabPresenter.js
  packages/tabs/src/presenters/Tabs.stylesheet.js
  packages/tabs/src/presenters/Tabs.stylesheet.test.js
  packages/tabs/src/presenters/TabsPresenter.js
  packages/tabs/src/presenters/TabsPresenter.stylesheet.test.js
  packages/theme-data/package.json
  packages/theme-data/src/baseTheme/components/button.js
  packages/theme-data/src/baseTheme/components/sideNav.js
  packages/theme-data/src/baseTheme/system/colorScheme.js
  packages/theme-data/src/basics/colors.js
  packages/theme-data/src/colorSchemes/darkBlue/components/button.js
  packages/theme-data/src/colorSchemes/darkBlue/components/sideNav.js
  packages/theme-data/src/colorSchemes/darkBlue/system/colorScheme.js
  packages/theme-data/src/colorSchemes/darkBlue/unresolvedRoles.js
  packages/theme-data/src/colorSchemes/darkGray/components/button.js
  packages/theme-data/src/colorSchemes/darkGray/unresolvedRoles.js
  packages/top-nav/src/presenters/__snapshots__/ProfileButtonPresenter.test.js.snap
  yarn.lock
Labels: release

#2240 feat: add dataVis color palette
  packages/accordion/package.json
  packages/avatar/package.json
  packages/banner/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/components/package.json
  packages/dropdown/package.json
  packages/flyout/package.json
  packages/icon-button/package.json
  packages/icons/package.json
  packages/input/package.json
  packages/label/package.json
  packages/modal/package.json
  packages/notifications-flyout/package.json
  packages/notifications-toast/package.json
  packages/profile-flyout/package.json
  packages/progress-bar/package.json
  packages/progress-ring/package.json
  packages/radio-button/package.json
  packages/rich-text/package.json
  packages/side-nav/package.json
  packages/skeleton-item/package.json
  packages/slider/package.json
  packages/spacer/package.json
  packages/storybook/package.json
  packages/surface/package.json
  packages/tabs/package.json
  packages/text-area/package.json
  packages/text-link/package.json
  packages/theme-context/package.json
  packages/theme-data/package.json
  packages/theme-data/src/baseTheme/components/dataVis.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-material-ui/package.json
  packages/timestamp/package.json
  packages/toggle/package.json
  packages/tooltip/package.json
  packages/top-nav/package.json
  packages/typography/package.json
  yarn.lock
Labels: theme data

#2241 feat: add theme-data for panel
  packages/theme-data/src/baseTheme/components/panel.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/densities/highDensity/components/panel.js
  packages/theme-data/src/densities/highDensity/unresolvedRoles.js
Labels: theme data

#2242 Release: July 14, 2020
  packages/accordion/package.json
  packages/avatar/package.json
  packages/banner/package.json
  packages/button/package.json
  packages/checkbox/package.json
  packages/components/package.json
  packages/dropdown/package.json
  packages/flyout/package.json
  packages/icon-button/package.json
  packages/icons/package.json
  packages/input/package.json
  packages/label/package.json
  packages/modal/package.json
  packages/notifications-flyout/package.json
  packages/notifications-toast/package.json
  packages/profile-flyout/package.json
  packages/progress-bar/package.json
  packages/progress-ring/package.json
  packages/radio-button/package.json
  packages/rich-text/package.json
  packages/side-nav/package.json
  packages/skeleton-item/package.json
  packages/slider/package.json
  packages/spacer/package.json
  packages/storybook/package.json
  packages/surface/package.json
  packages/tabs/package.json
  packages/text-area/package.json
  packages/text-link/package.json
  packages/theme-context/package.json
  packages/theme-data/package.json
  packages/theme-data/src/baseTheme/components/dataVis.js
  packages/theme-data/src/baseTheme/components/panel.js
  packages/theme-data/src/baseTheme/unresolvedRoles.js
  packages/theme-data/src/densities/highDensity/components/panel.js
  packages/theme-data/src/densities/highDensity/unresolvedRoles.js
  packages/theme-material-ui/package.json
  packages/timestamp/package.json
  packages/toggle/package.json
  packages/tooltip/package.json
  packages/top-nav/package.json
  packages/typography/package.json
  yarn.lock
Labels: release

#2246 fix: dismissButtonTitle prop was not working
  packages/banner/src/BannerPresenter/BannerPresenter.js
  packages/banner/src/BannerPresenter/presenters.js
  packages/banner/src/__stories__/stories.js
Labels: bug, community

#2247 Release: July 16, 2020
  packages/banner/README.md
  packages/banner/package.json
  packages/banner/src/Banner.js
  packages/banner/src/Banner.test.js
  packages/banner/src/BannerAction/BannerAction.js
  packages/banner/src/BannerAction/BannerAction.test.js
  packages/banner/src/BannerAction/__snapshots__/BannerAction.test.js.snap
  packages/banner/src/BannerAction/stylesheet.js
  packages/banner/src/BannerInteractions/BannerInteractions.js
  packages/banner/src/BannerInteractions/BannerInteractions.test.js
  packages/banner/src/BannerInteractions/__snapshots__/BannerInteractions.test.js.snap
  packages/banner/src/BannerInteractions/stylesheet.js
  packages/banner/src/BannerPresenter/BannerPresenter.js
  packages/banner/src/BannerPresenter/BannerPresenter.test.js
  packages/banner/src/BannerPresenter/__snapshots__/BannerPresenter.test.js.snap
  packages/banner/src/BannerPresenter/presenters.js
  packages/banner/src/BannerPresenter/stylesheet.js
  packages/banner/src/__snapshots__/Banner.test.js.snap
  packages/banner/src/__stories__/stories.js
  packages/banner/src/presenters/IconBackground/IconBackground.js
  packages/banner/src/presenters/IconBackground/index.js
  packages/banner/src/presenters/IconBackground/stylesheet.js
Labels: release

#2249 fix: hover styles take precedent over focus
  packages/dropdown/src/__snapshots__/Dropdown.test.js.snap
  packages/dropdown/src/presenters/__snapshots__/InputPresenter.test.js.snap
  packages/input/src/presenters/InputHaloPresenter.stylesheet.js
  packages/input/src/presenters/__snapshots__/InputHaloPresenter.test.js.snap
  packages/storybook/gemini/chromeReact/Dropdown/default/default - clicked/chromeReact.png
  packages/text-area/src/__snapshots__/TextArea.test.js.snap
Labels: bug

#2250 Release: July 28, 2020
  packages/dropdown/src/__snapshots__/Dropdown.test.js.snap
  packages/dropdown/src/presenters/__snapshots__/InputPresenter.test.js.snap
  packages/input/src/presenters/InputHaloPresenter.stylesheet.js
  packages/input/src/presenters/__snapshots__/InputHaloPresenter.test.js.snap
  packages/storybook/gemini/chromeReact/Dropdown/default/default - clicked/chromeReact.png
  packages/text-area/src/__snapshots__/TextArea.test.js.snap
Labels: release
